// ─── Section components barrel export ────────────────────────────────────────
export { AboutPreview } from './AboutPreview'
export { GlobalMap } from './GlobalMap'
export { Initiatives } from './Initiatives'
export { Testimonials } from './Testimonials'
export { MilestonesPreview } from './MilestonesPreview'
export { CorePillars } from './CorePillars'
export { ImpactStats } from './ImpactStats'
export { GalleryPreview } from './GalleryPreview'
export { CtaSection } from './CtaSection'
